baseurl = "https://ixday.github.io/"
languageCode = "en-us"
title = "Not today..."
googleAnalytics = "UA-38228870-1"

theme = "chunk"

pygmentsUseClassic=true
pygmentsUseClasses = true
PygmentsCodeFences = true


[[menu.main]]
  name = "github"
  identifier = "about"
  url = "https://github.com/IxDay"

[Params]
  author = "IxDay"
  epitaph = "Done with love... and beer"
  showCategories = true
  remark42SiteID = "blog"
  remark42Url = "https://remark42.rulz.xyz"
