baseurl = "https://ixday.github.io/"
languageCode = "en-us"
title = "Not today..."
googleAnalytics = "UA-38228870-1"

theme = "chunk"

pygmentsUseClassic=true
pygmentsUseClasses = true
PygmentsCodeFences = true
disqusShortname = "IxDay"

[[menu.main]]
  name = "github"
  identifier = "about"
  url = "https://github.com/IxDay"

[Params]
  author = "IxDay"
  epitaph = "Done with love... and beer"
  showCategories = true
